// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Message struct {
	ID        int64        `json:"id"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PendingMessage struct {
	ID        int64        `json:"id"`
	Content   string       `json:"content"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}
